### ISSUE TITLE
CSS for report display console warnings for IE compatibility

### ISSUE THREAD

**Issue by mems** [gruntjs/grunt-contrib-less#154]
When using `data-uri()` function, if the size of a file to embed exceeds IE8 data URI limit of 32KB, by default `ieCompat=true` will display this message: 

> Skipped data-uri embedding of %s because its size (%dKB) exceeds IE8-safe %dKB!

But in the `minify` function, `toCSS()` is called twice. **Why twice, whatsoever if report is used or not?**

Also, the "max"/non-minified version is called without any options, this is why this warning is displayed too when `ieCompat=false`.

**All options that have any impact to the generated (non-minified) output should be passed.** Like ieCompat, strictMath, strictUnits, importMultiple and urlArgs (sourceMap? Which also add a comment to the EOF)

```
var minify = function (tree, options) {
    var result = {
      min: tree.toCSS(options)
    };
    if (/*TODO: Condition = only if report is required*/!grunt.util._.isEmpty(options)) {
      result.max = tree.toCSS(/*TODO: Pass options like: ieCompat, strictMath, strictUnits...*/);
    }
    return result;
  };
```

**Comment by lukeapage** [comment]
this is fixed - toCSS is no longer called twice.
