### ISSUE TITLE
import options is not working

### ISSUE THREAD

**Issue by vinngn** [gruntjs/grunt-contrib-less#177]
As follow http://lesscss.org/features/#import-options I do:

/* Twitter Bootstrap */
@import (inline) "../common/bootstrap.css";

And when do grunt recess i get the following error:
>> Parser error in main.less
>>        3.     /* Twitter Bootstrap */
>>        4.     @import (inline) "../common/bootstrap.css";
>>        5. 

In order to make it work the way I want, I have to rename bootstrap.css to boostrap.less and import the less file.

**Comment by lukeapage** [comment]
> grunt recess

this is grunt-contrib-less

recess uses a very old version of less. I suggest moving to grunt-contrib-less.
