### ISSUE TITLE
[Question] How compress with comments remove?

### ISSUE THREAD

**Issue by a-h-abid** [gruntjs/grunt-contrib-less#191]
Hi, new to grunt and less.

I'm looking for option to remove comments with compressing. How can I do it? Setting compress to true doesn't seem to remove the comments. My current settings:

```
options: {
    compress: true,
    yuicompress: true,
    optimization: 1
}
```

Googled around but not able to find required answer.

**Comment by MathRobin** [comment]
Hi, this is not a complete answer. Here we know that if we use `--clean-css` option, it removes the classical comments `/* .... */`, but not the "block comments" `/*! .... */`. So how to remove them too ?
