### ISSUE TITLE
calc issue

### ISSUE THREAD

**Issue by stevenvachon** [gruntjs/grunt-contrib-less#195]
In the browser and the command-line with Less, I have no issues using `calc()`, but using grunt-contrib-less produces
```
>> OperationError: Operation on an invalid type in stylesheets/common.less on line 55, column 2:
>> 54 	overflow-x: hidden;
>> 55 	padding-top: calc( var(--header-height) + 1rem );
>> 56 	position: relative;
```

**Comment by gwicksted** [comment]
Curious, does this work?

calc(var(--header-height) ~"+" 1rem);

**Comment by seven-phases-max** [comment]
@gwicksted 

Yes, Less will compile `calc(var(--header-height) ~"+" 1rem);` to calc(var(--header-height) + 1rem); as expected.

**Comment by PawelOwczarekFalcon** [comment]
I found solution:
http://gillianshelpdesk.tumblr.com/post/127773807047/calc-issues-in-grunt-contrib-less

**Comment by XhmikosR** [comment]
Does this still happen with the latest release?

**Comment by rodrigobacelli** [comment]
@XhmikosR yeah, unfortunately

**Comment by XhmikosR** [comment]
I need a full test case I can use to reproduce this...

**Comment by XhmikosR** [comment]
I can't reproduce this. I [added a test case](https://github.com/gruntjs/grunt-contrib-less/commit/5501c3b6fcbbe9b811e2cdf8aa6bf3d9d93d7020) and passes fine with the latest master, so I'm closing the issue.
