### ISSUE TITLE
Multiple less files & sourcemap

### ISSUE THREAD

**Issue by tleunen** [gruntjs/grunt-contrib-less#196]
Hi,

I'm generating a single output file from multiple less files, but at the end, I'd like a single sourcemap. (Unless there is something I didn't understand.)

Unfortunately, I don't know how to achieve this. When I run my task, this is the output:
```
Reading example1.less...OK
Writing Example.css.map...OK
File Example.css.map created.
Reading example2.less...OK
Writing Example.css.map...OK
File Example.css.map created.
Writing Example.css...OK
File Example.css created
```
So the sourcemap is always overwritten when LESS parse a new file.

My grunt task looks like this:
```
less: {
            dist: {
                options: {
                    sourceMap: true,
                    sourceMapFilename: "Example.css.map",
                    sourceMapBasepath: "assets/css"
                },
                files: {
                    "Example.css": ["assets/css/example1.less", "assets/css/example2.less"]
                }
            }
        },
```

Instead of having multiple files, should I create a single "main" less files with only imports?

Thanks.

**Comment by sindresorhus** [comment]
https://github.com/gruntjs/grunt-contrib-less/pull/243#issuecomment-75196554

**Comment by gelus** [comment]
[#243 (comment)](https://github.com/gruntjs/grunt-contrib-less/pull/243#issuecomment-75565337)
