### ISSUE TITLE
First line of CSS source not output

### ISSUE THREAD

**Issue by leigeber** [gruntjs/grunt-contrib-less#201]
If I include a CSS file as as source the first line is skipped, nothing is pulled into the destination. Any line after the first is compiled in.

```
.test1 {color:red}
.test2 {color:blue}
```

Only the test2 class would be joined with the other sources.

**Comment by lukeapage** [comment]
can you elaborate on your example? it sounds fundamental, but I think that is unlikely so there must be something else you are doing.
