### ISSUE TITLE
@import (once) not working as expected with multiple src files

### ISSUE THREAD

**Issue by rmunson** [gruntjs/grunt-contrib-less#203]
It seems like the @import (once) directive-option pair is not working as expected with multiple src files being added to a single dest file.  
With a set of less files using the import (once) directive to include a common file - 
shared.less : 
```
.shared-rule { /*..*/}
```
a.less :
```
@import (once) "shared"
.a-rule {/*..*/}
```
b.less :
```
@import (once) "shared"
.b-rule {/*..*/}
```

If you include a and b as src files in a single dest :
```
{
	dist: {
		files : {
			"a-b.css" : [
				'a.less',
				'b.less'
			]
		}
	}
}
```

shared.less is currently imported twice, as each file is parsed separately.
a-b.css:
```
.shared-rule { /*..*/}
.a-rule {/*..*/}
.shared-rule { /*..*/}
.b-rule {/*..*/}
```

This does work, however, if you create a master .less file that imports a and b.

a-b.less:

```
@import "a.less"
@import "b.less"
```

```
{
	dist: {
		files : {
			"a-b.css" : "a-b.less"
		}
	}
}
```

This is a suitable workaround, but limits the flexibility of the build config, especially when dealing with multiple build targets from the same set of assets.

**Comment by gelus** [comment]
pull #243

**Comment by sindresorhus** [comment]
https://github.com/gruntjs/grunt-contrib-less/pull/243#issuecomment-75196554
