### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by Torone** [gruntjs/grunt-contrib-less#208]
It will be nice to add in the documentation the option to import references.
What I did is the code below to let it work fine but has been a challenge to find it:

```javascript
less: {
			development: {
				options: {
					imports: {
						reference: [
							'css/variables.scss',
							'css/mixins.scss'
						]
					}
				},
				files: [
					{
						expand: true,
						cwd: 'myPath',
						src: ['*.less', '!{var,mix}*.less'],
						dest: 'css/',
						ext: '.css'
					}
				]
			}
		}
```

**Comment by lukeapage** [comment]
the test file does not surround files with `[]` and it works fine. are you sure this is still a problem?

**Comment by alundiak** [comment]
I don't have this issue now. Node 0.10.35, npm 1.4.28.
