### ISSUE TITLE
-webkit, -moz, -o etc. line erased

### ISSUE THREAD

**Issue by GianLaz** [gruntjs/grunt-contrib-less#209]
Hi,
line of code like these are missing in the compiled css file. Examples:

```css
background-image: -webkit-linear-gradient(left, @gr1, @gr2, @gr1);
-moz-transition: all 0.2s;
-ms-transition: all 0.2s;
```

How can i fix this issue?
Thanks

**Comment by lukeapage** [comment]
Can you give more information? for instance a file where this goes wrong and what options you use?
