### ISSUE TITLE
Grunt less task leaves @imports in the middle of the output file

### ISSUE THREAD

**Issue by hsz** [gruntjs/grunt-contrib-less#210]
I have set a simple Grunt less task that compiles two files:

    less: {
      development: {
        files: {
          'dist/css/app.css': [
            'src/vendor/normalize-css/normalize.css',
            'src/less/app.less'
          ]
        }
      }
    }

`normalize.css` contains regular CSS content.

My `app.less` starts with:

    @import url(http://fonts.googleapis.com/...);

The generated output file has a content in which my `@import` font rule appears in the middle of the file. 

According to the [W3 At-rules reference][1] all `@import` directives that are not on the top of the file are ignored.

Is it possible to force all `@imports` to be moved to the top of the output file?

  [1]: http://www.w3.org/TR/CSS21/syndata.html#at-rules

**Comment by sindresorhus** [comment]
Use `@import` instead of the concat "feature".
