### ISSUE TITLE
Sourcemap not working

### ISSUE THREAD

**Issue by michaelDotco2** [gruntjs/grunt-contrib-less#221]
I am running the production version of the grunt task below and the source map is beeing generated but it wont work ikn the web developer tools for firefox where i normally look at these things. Does anyone know what the problem is?

```js
 less: {
dev: {
    options: {
        sourceMap: true,
        dumpLineNumbers: 'comments',
    },
    files: {
        'static/css/custom-bootstrap.css': 'dev-tools/custom-less/custom-bootstrap.less',
    }
},
production: {
    options: {
        sourceMap: true,
        sourceMapFilename: 'static/css/custom-bootstrap.min.css.map',
        sourceMapRootpath: '/Users/michaelcoyne/Sites/brewershome/',
        sourceMapURL: 'static/css/custom-bootstrap.min.css.map',
        cleancss: true
    },
    files: {
        'static/css/custom-bootstrap-min.css': 'dev-tools/custom-less/custom-bootstrap.less',
    }
}

},
```

**Comment by ddprrt** [comment]
@geekyMoa Did you diff the compiled CSS files? Sourcemaps have to be linked via comment in the CSS output, maybe the path is different and thus Chrome can't find the referred map. Might be the same issue for @michaelDotco2

**Comment by nhall** [comment]
I wonder if this is related to #236. Seems to be my problem.

**Comment by geekyMoa** [comment]
@ddprrt Sorry for late reply, but yes, I did diff the compiled CSS files and there was no difference. It's been a while though, I haven't tried it lately.
