### ISSUE TITLE
'banner' Value Ignored When 'cleancss' is Set to True

### ISSUE THREAD

**Issue by Magnitus-** [gruntjs/grunt-contrib-less#227]
What the title says.

If you have this:

options: {
    cleancss: true,
     banner: '/*Some Short Copyright Notice*/'
}

The copyright notice won't be generated on top of the minified output file(s).

Not sure if that is by design, but it's definitely not what I was expecting.

**Comment by juanbrujo** [comment]
Just curious, why the `!` character has to be used at the beginning for banner display?

**Comment by lukeapage** [comment]
clean css removes comments. You can stop it removing by using `/*!` or you can change the options into clean-css - https://github.com/jakubpawlowicz/clean-css

Closing as this is not a grunt-contrib-less issue.

**Comment by Magnitus-** [comment]
Ok, I hadn't put ! in the banner string in my options, because I assumed the banner got added after minification, not before.

I guess it's a matter of ordering. The user just needs to know that the banner gets added before the file gets minified by clean-css. 

I'm not sure it is the most intuitive way (for the user) to implement it, but it is what it is I guess, but that's another topic entirely.

**Comment by luobotang** [comment]
I'll go to add a `!` to my banner string....
