### ISSUE TITLE
Source Map not working with cleancss?

### ISSUE THREAD

**Issue by FezVrasta** [gruntjs/grunt-contrib-less#229]
I'm trying to get this task:

compile less to css and create source map
compile less to css minifying it and create source map
run autoprefixer which edits both the CSS and the source map (this step can be removed and the problem is still there)

When I use the not minified version of the files, the source maps work correctly.
When instead I try to use the minified versions, the source map doesn't work and points just to the "main.less" file that includes the imports.

**Comment by lukeapage** [comment]
sourcemap support was only added to clean css recently.
If you use the new v1 release of grunt contrib less and use https://github.com/less/less-plugin-clean-css then sourcemaps will work.
