### ISSUE TITLE
support globalVars option

### ISSUE THREAD

**Issue by fde31** [gruntjs/grunt-contrib-less#240]
The grunt task currently only supports the modifyVars option in order to inject/alter variables programmatically from the task options. Just recently I came across two use cases where I'd like to set global vars at the top of the files in the grunt task of a project referencing less files from a separate theme project as decribed in http://lesscss.org/usage/#command-line-usage-global-variable. Any chance to get this?

Looking at the code it seems like most of the infrastructure for adding this is already available and one just needs to prepend the parsed vars to the .less source. I can go ahead and add that myself and file a PR incl. tests etc if desirable.

**Comment by lukeapage** [comment]
You dont need to prepend anything, just pass the option to less.

**Comment by lukeapage** [comment]
The mofify vars code can be removed too - i suspect its added once by less
and once by grunt contrib less. I also suspect globalVars will just work
(in the latest version of grunt contrib less)

**Comment by fde31** [comment]
Oh sorry, totally missed replying to this. You are right, passing the option down to less works properly here for me and there is therefore no need to change contrib-less as less itself is already supporting the parsing properly. Thanks!
