### ISSUE TITLE
How specify list of LESS files as source under a specific folder

### ISSUE THREAD

**Issue by ohmirocks** [gruntjs/grunt-contrib-less#241]
Hi, 

I have lot of LESS file under a less folder. how to i mention in my grunt task to generate .css file for all these less file. i don't want to each file separately.

Something like this 

files: ['src/**/*.css'], ['src/**/*.less']

**Comment by sindresorhus** [comment]
Read the grunt docs. It's all in there.

http://stackoverflow.com/questions/15344584/grunt-0-4-less-task-how-to-not-concatenate-destination-files/15371443#15371443
