### ISSUE TITLE
How to import lesshat into every compiled .less file.

### ISSUE THREAD

**Issue by elhoucine** [gruntjs/grunt-contrib-less#248]
Hello,

In grunt-contrib-stylus there is a import option:

### import

Type: `Array`

Import given stylus packages into every compiled `.styl` file, as if you wrote `'@import '...'` in every single one of said files.

```
...
options: {
                    compress: false,
                    use: [ require('kouto-swiss') ],
                    import: [ 'kouto-swiss' ]
                },
...
```

How can I do the same thing with lesshat in grunt-contrib-less  ?

Thanks

**Comment by sindresorhus** [comment]
The issue tracker is for actual issues. Use StackOverflow for support questions.
