### ISSUE TITLE
Banner option ignored

### ISSUE THREAD

**Issue by brantleye** [gruntjs/grunt-contrib-less#252]
In the following configuration, the banner option is ignored.

```js
less: {
  dist: {
    options: {
      banner: 'Test banner'
    },
    files: {
      'dist.css': ['src.less']
    }
  }
}
```

**Comment by XhmikosR** [comment]
Doesn't seem to happen with the latest master since our tests pass.

If you still have this issue, please provide a complete test case with all the needed files to reproduce the issue.
