### ISSUE TITLE
Nested @import showing "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by ah-arch** [gruntjs/grunt-contrib-less#256]
I have set up 2 files, one of which imports the other:
*test.less*:

```less
.test {
    @import 'test2';
}
```

*test2.less*:

```less
.test2 {
    color: blue;
}
```

This compiles fine using the less compiler as well as the maven less plugin. However, there are errors using this plugin.

- v0.9.0:  `SyntaxError: Cannot read property 'length' of undefined in test.less on line null, column 0`
- v1.0.0:  `TypeError: Cannot read property 'length' of undefined`

**Comment by MojoJojo** [comment]
Yeah. Facing same issue with nested/scoped imports. The error message is not too descriptive either. Were you able to get it to work? Any workarounds?

**Comment by MojoJojo** [comment]
Okay, I think I figured it out. You need to set strictImports: false in your gruntfile. As per https://github.com/less/less.js/issues/656, scoped and nested imports are only allowed if strictimports is set to false. Setting it to false resolved my issue.
