### ISSUE TITLE
Slow compiling time when watching and compiling 117 files

### ISSUE THREAD

**Issue by bensinclair** [gruntjs/grunt-contrib-less#261]
I have split my LESS files up into about 117 files. Each file is dedicated to it's own area making it easier to find what I'm looking for and then I simply import those files into each other to form one big file.

Is a 1.5 seconds compiling time considered slow?

I was using [LiveReload](http://livereload.com/) and would really like to move to Grunt. However, LiveReload was compiling in about 200ms. But Grunt seems to be running at 1.5 seconds. I've read about slow downs when monitoring 1,000's of files, but 100's?

I am testing on an iMac with an i7 CPU, SSD and 16GB RAM. I am running Grunt locally and not inside a VM.

Here my code that basically tells Grunt to watch all .less files in the less folder and then compile the one file.

```
watch: {
	less: {
	  files: [
			'less/**/*.less',
	  ],
		tasks: ['less']
	},
},
less: {
  development: {
    files: {
      "dist/style.css": "less/style.less"
    }
  }
}
```

Any suggestions on how I can format my code to compile much faster? Or is this a limitation of this library at the moment?

**Comment by sindresorhus** [comment]
Questions are better asked on StackOverflow.

This might be caused by both grunt and grunt-contrib-watch having a considerable startup/reload overhead.
