### ISSUE TITLE
How to use wildcards for src\dest?

### ISSUE THREAD

**Issue by jt000** [gruntjs/grunt-contrib-less#262]
In my project I have multiple LESS files that all need to be individually built to CSS. In Gulp what I did was keep all the files to convert in the top folder & all the import LESS files in a child folder. For example:

```
   less
   + -- index.less
   + -- about.less
   + -- imports
         + -- nav.less
         + -- menu.less
         + -- variables.less   
```

To handle this in grunt-contrib-less it would seem that each file to be built would need their own task, since all source files appear to get concatenated into a single CSS. For example:

```javascript
        less: {
           index: {
                src: '<%= config.src %>/assets/less/index.less',
                dest: '<%= config.dest %>/assets/css/index.css',
            },
           about: {
                src: '<%= config.src %>/assets/less/about.less',
                dest: '<%= config.dest %>/assets/css/about.css',
            }
        }
```

Seems what I should be able to do is something like:

```javascript
        less: {
           main: {
                src: '<%= config.src %>/assets/less/*.less',
                dest: '<%= config.dest %>/assets/css/',
            }
        }
```
 But this causes an EISDIR error. Am I doing something wrong or is this behavior not supported?

**Comment by sindresorhus** [comment]
This has been answered so many times before, both on this very same issue tracker and StackOverflow. Please take some time to read the grunt docs before using it. Thanks.

http://stackoverflow.com/questions/15344584/grunt-0-4-less-task-how-to-not-concatenate-destination-files/15371443#15371443
