### ISSUE TITLE
sourceMap creation displays "undefined" as filename

### ISSUE THREAD

**Issue by mcnesium** [gruntjs/grunt-contrib-less#264]
When running the task without declaring `sourceMapFilename` it correctly saves the mapfile with the same name as the css file adding `.map`to it, and also correctly sets the path in the css file, but in the console output it says **undefined**:

    Running "less:default" (less) task
    File undefined created.
    File css/style.css created

this is using v1.0.0 and grunt v0.4.5

edit: hold on, it does NOT set the path correctly. this is propably related to #236

**Comment by onionhammer** [comment]
:+1: Im also getting this

**Comment by timmd909** [comment]
Got the same problem. Seems the source map output is using the root instead of the working directory when creating the paths in the source map.

**Comment by phairoh** [comment]
This seems to have been fixed a [a long time ago](https://github.com/gruntjs/grunt-contrib-less/commit/e89eed4d7c85e3f1145ec734e5c567d825fbfc66#diff-38b2b12bdd335f3b3e888c5caf03222d) but apparently the npm registry has not been updated.

**Comment by JackWH** [comment]
@phairoh Thanks. When is the npm registry likely to be updated with this?

**Comment by mrmlnc** [comment]
Confirmed in v1.0.1

```
Running "styles" task

Running "less:dev" (less) task
File undefined created.
File build/styles/styles.css created

Done, without errors.
```
