### ISSUE TITLE
ParseError: Unrecognised input 

### ISSUE THREAD

**Issue by amrutha-rajiv** [gruntjs/grunt-contrib-less#265]
I see an issue  with  v1.0.0
>> ParseError: Unrecognised input in less/xx.less on line 128, column 12:
>> 127 .stuff {
>> 128     display: inline-block;
>> 129     vertical-align: top;

**Comment by XhmikosR** [comment]
Most likely an issue with LESS itself or your files.

Try the latest release and if the issue still happens report back with more info, sample code etc.
