### ISSUE TITLE
Unable to compile mixins with default paramaters

### ISSUE THREAD

**Issue by ralphsmith80** [gruntjs/grunt-contrib-less#266]
This is actually a broken issue with less@2.5.0 but since I'm using grunt-contrib-less and that uses less@^2.4.0 which pulls less@2.5.0 causing grunt-contrib-less to also break I figured you might want to tighten up your dependency list for grunt-contrib-less@1.0.0 to less@2.4.0. I've tested this and it is working. To fix it for now I've rolled back to grunt-contrib-less@0.12.0.

Related [less issue](https://github.com/less/less.js/issues/2542).

Here's a test case that breaks
``` css
.opacity(@op:100) {
    filter:alpha(opacity=@op);
    -moz-opacity:@op/100;
    -khtml-opacity:@op/100;
    opacity:@op/100;
}
body {
  .opacity();
}
```

**Comment by vladikoff** [comment]
@ralphsmith80 1.0.1 is on npm with the version lock to avoid compat issues.
