### ISSUE TITLE
Plugin autoprefix does nothing

### ISSUE THREAD

**Issue by janbaer** [gruntjs/grunt-contrib-less#270]
I tried to integrate the autoprefix-plugin, but it did nothing. I also tried the tip from @rindybo, but it hasn't helped.

This is the output when I'm starting grunt with the --verbose option

```
Running "less:development" (less) task
Verifying property less.development exists in config...OK
Files: public/css/styles.less -> public/css/styles.css
Options: banner="", sourceMap=false
Reading public/css/styles.less...OK
Writing public/css/styles.css...OK
File public/css/styles.css created
```

I've installed the latest versions of both components.

**Comment by ThisIsManta** [comment]
Hi Janbaer,

I had the same problem as you did when I used **grunt-contrib-less** version _0.9.0_. Now, I upgraded to _1.2.0_ and the problem is gone.

**Comment by janbaer** [comment]
Thanks! I also updated it in my project and now it works!

**Comment by rBurgett** [comment]
I am currently running `grunt-contrib-less` version 1.2.0 and `less-plugin-autoprefix` version 1.5.1 and it does not seem to be doing anything. I have been playing with it for two hours now with no luck. My Gruntfile contains this config:
```
less: {
  development: {
    files: {
      'dist/css/main.css': 'less/*.less'
    },
    plugins: [
      new (require('less-plugin-autoprefix'))({browsers: ['last 2 versions']})
    ]
  }
}
```
I can't figure out what is wrong or what I am missing. I am running the latest versions. Any ideas?

Thanks!

**Comment by rBurgett** [comment]
I figured it out. Plugins needed to be under options. Brilliant!
```
less: {
  development: {
    files: {
      'dist/css/main.css': 'less/*.less'
    },
    options: {
      plugins: [
        new (require('less-plugin-autoprefix'))({browsers: ['last 2 versions']})
      ]
    }
  }
}
```
