### ISSUE TITLE
npmjs.com usage examples

### ISSUE THREAD

**Issue by tgreenpubco** [gruntjs/grunt-contrib-less#275]
I had a bit of trouble getting the plugins to work. The usage examples show to use:

```javascript
new require('less-plugin-autoprefix')({browsers: ["last 2 versions"]})
```
This never showed any plugins when running --verbose and would trigger errors.

This did work for me:
```javascript
new (require('less-plugin-autoprefix'))({browsers: ["last 20 versions"]})
```

I'm a total node noob so that could be my issue ;)

**Comment by XhmikosR** [comment]
This seems to be fixed.
