### ISSUE TITLE
How to import once...  

### ISSUE THREAD

**Issue by MoonTahoe** [gruntjs/grunt-contrib-less#277]
I have a File APP.less, it imports Bootstrap.less and some styles.  I have multiple less files that @import the APP.less file only, this way they have access to Bootstrap.less in these child files.

It seems that every time APP.less is imported it duplicates the styles in that file as well as everything imported.

I am only building the child files, and not the app, but every child file that gets built includes a __copy__ of APP.less and it's dependencies.

```javascript
   files: {
      "dist/css/style.css": [
          "less/*.less",
          "!(less/APP.less)"
      ]
  }
```

APP.less --> @imports Bootstrap, both app and bootstrap not part of grunt task
|
|----  Child_1 --> @imports APP.less, is getting processed by grunt
|
|----  Child_2 --> @imports APP.less, is getting processed by grunt
|
|----  Child_3 --> @imports APP.less, is getting processed by grunt

Building the three children adds 3 copies of APP.less to output as well as 3 copies of Bootstrap.less.

In the Children I use:

                 @import (once) "APP.less"

How do I make it so the dependencies are only included once?...

**Comment by evan-wise** [comment]
I have run into a similar issue. The plugin compiles each file separately and then concatenates the results. To work around this, either concatenate the files first (LESS's default behavior for duplicate `@import` statements is to include them only once, so this is okay), or generate a single LESS file which `@import`s the desired files and compile this.

**Comment by sateffen** [comment]
The simplest way is to have ONE start file.
You activly tell the grunt task to compile EVERY less file separatly, and concat them, because you use the minimatch pattern.

If you write something like

```
files: {
    "style.css": "style.less"
}
```

with the style.less file looking like:

```
@import APP;
@import child_1;
@import child_2;
@import child_3;
```

less will compile everything in ONE step, so less will handle everything for you, without any duplications.
