### ISSUE TITLE
always running task , no output & endless loop

### ISSUE THREAD

**Issue by Phinome** [gruntjs/grunt-contrib-less#279]
i was in some trouble. i try to compile less files with grunt , but i found less task always running , no output , and endless loop. i try to solve this problem the whole afternoon, but clueless. 

likes this:

![less task](https://cloud.githubusercontent.com/assets/1940194/7827559/6df2dc7c-045b-11e5-9609-0c4bb2a64758.png)

my section Gruntfile.js like this:

```javascript

less: {
      dist: {
        options: {
          plugins: [
            new (require('less-plugin-autoprefix'))({ browsers: ["last 2 versions"] }),
            new (require('less-plugin-est'))()
          ]
        },
        //        files: [
        //          { expand: true, cwd: 'src/common/less/', ext: '.css', dest: 'src/common/css/', src: ['**/*.less'] }
        //        ]
        files: {
          "src/index/index.css": "src/index/index.less"
        }
      }
    },
   grunt.loadNpmTasks('grunt-contrib-less');

   grunt.registerTask('less', ['less:dist']);

```

oh, my develop environment list:

Yosemite ,
node version : v0.12.2
grunt version : v0.4.5
grunt-cli version : v0.1.13
grunt-contrib-less version :  current release
lessc version : 2.5.0

that's all.

Thanks ~ 😀

**Comment by vladikoff** [comment]
` grunt.registerTask('less', ['less:dist']);`

**Comment by vladikoff** [comment]
Rename your task `grunt.registerTask('myLess', ['less:dist']);`

This is happening because `grunt less` runs the root less task

**Comment by vladikoff** [comment]
http://gruntjs.com/frequently-asked-questions#why-am-i-getting-a-maximum-call-stack-size-exceeded-error

**Comment by Phinome** [comment]
Thanks.😀
