### ISSUE TITLE
Show warnings when extend() has no matches

### ISSUE THREAD

**Issue by keithjgrant** [gruntjs/grunt-contrib-less#283]
When using `extend()`, Less' warning about missing classes are not output.

```less
.foo {
    &:extend(.bar);  // .bar is undefined
}
```

Using lessc logs the warning "extend ' .bar' has no matches. Using grunt-contrib-less, these warnings are swallowed.

**Comment by XhmikosR** [comment]
I guess this is related to #314. Closing this one since that one is has a PR referenced.

**Comment by galvarez421** [comment]
This issue does not appear to be fixed as of v1.4.1 despite the change mentioned.
