### ISSUE TITLE
Issue with Safari 9

### ISSUE THREAD

**Issue by YouriT** [gruntjs/grunt-contrib-less#291]
Hi,

Wanted to know wether some other people do also have an issue with Safari 9 ?

My problem appeared with ```compress: false``` if compress is true then no issue.

The result of the issue is your page completely fucked up with kind of half CSS loaded and no error in the console.

If someone has the same issue would be delighted to know how to solve it.

Thanks.

**Comment by jedateach** [comment]
This might be an issue with keyframes styles having a semicolon after them. Had the same issue.

**Comment by jedateach** [comment]
Could be related: https://github.com/less/less.js/issues/2357

**Comment by sindresorhus** [comment]
Issues with the output belong in the LESS issue tracker.
