### ISSUE TITLE
can not fuound module less-plugin-autoprefix

### ISSUE THREAD

**Issue by HaifengPeng** [gruntjs/grunt-contrib-less#294]
As the question. I get this error by the example...

**Comment by dominikwilkowski** [comment]
Make sure you install [less-plugin-autoprefix](https://github.com/less/less-plugin-autoprefix).
Use `"less-plugin-autoprefix": "^1.5.1",` in your `package.json` or run:
```shell
npm install -g less-plugin-autoprefix
```
