### ISSUE TITLE
Rendered CSS colours are uppercased

### ISSUE THREAD

**Issue by qasimalyas** [gruntjs/grunt-contrib-less#295]
I've come across an issue where I migrated from version 1.0.1 to version 1.1.0. I recompiled my .less files and my output colours are rendered from lowercase to uppercase. 

```#e1e1e1``` to ```#E1E1E1```

Is there an option to stop this from happening? I couldn't see any applicable options on the [main page](https://github.com/gruntjs/grunt-contrib-less).

I know this is purely cosmetic but I have quite a large codebase which would require a rebuild and deploy which I do want to avoid at this stage.

**Comment by mackensen** [comment]
I'm seeing this as well; rolling back to `~1.0.0` eliminates the issue.

**Comment by jrcryer** [comment]
Out of interest - which platform are you both on @mackensen and @qasimalyas? I've tested it my end and can't see an issue.  One potential is a difference between less `2.4.*` and `2.5.*`.  I was wondering whether you'd tried to run less outside of the plugin and had the same result?

**Comment by mackensen** [comment]
@jrcryer OSX 10.11.2. I think you're right about the `less` version. I ran ran `lessc` (`2.5.3`) manually and it uppercased the colors. That's the same version grunt's installing.

**Comment by seven-phases-max** [comment]
Most likely this is related to Less preserving hex color values now. Thus you get them uppercase in the resulting CSS because they *are* uppercase in your sources (i.e. it does not make those uppercase now but did make them lowercase before 2.5.2).

**Comment by XhmikosR** [comment]
This is an upstream issue.
