### ISSUE TITLE
add comment block to compiles .css

### ISSUE THREAD

**Issue by JacobLett** [gruntjs/grunt-contrib-less#300]
Is it possible to add a comment block to the compiled css file? I would like to add some instructions to the top informing any developers who pick up the file that there are source less files. It is possible some developers may not be familiar with less and I would like to prevent overwriting any changes they make at a later time.

Thank you.

**Comment by notethis** [comment]
@JacobLett I believe what you are looking for is the 'banner' option?

**Comment by XhmikosR** [comment]
See the previous comment.
