### ISSUE TITLE
Sourcemaps: sourceMappingURL is not added to css output

### ISSUE THREAD

**Issue by xeroxoid** [gruntjs/grunt-contrib-less#303]
It seems that the expected ```/*# sourceMappingURL=app.css.map */``` is never added to my output css file..
The ```app.css.map``` file is created properly though.

Using latest version 1.2.0

My config:

```javascript
    less: {
      options: {
        paths: [
          '<%= yeoman.client %>/bower_components',
          '<%= yeoman.client %>/app',
          '<%= yeoman.client %>/components'
        ],
        sourceMap: true,
        sourceMapURL: 'app.css.map',
        sourceMapRootpath: '/'
      },
      server: {
        files: {
          '.tmp/app/app.css' : '<%= yeoman.client %>/app/app.less'
        }
      },
    },
```

**Comment by matt-bailey** [comment]
I seem to be having the same problem - map file gets generated but `sourceMappingURL` not added to CSS files.

Version 1.2.0.

Config:
```javascript
module.exports = {
  options: {
    paths: ["twg-src/less"],
    compress: true,
    sourceMap: true
  },
  files: {
    expand: true,
    cwd: "twg-src/less",
    src: "*.less",
    dest: "twg-src/css",
    ext: ".css",
    flatten: true
  }
};
```

**Comment by xeroxoid** [comment]
After losing a couple of hours on the issue I found that for me it autoprefixer was overwriting the sourceMappingUrl in the generated CSS file. Quick fix for that:

    // Add vendor prefixed styles
    autoprefixer: {
      options: {
        browsers: ['last 2 versions'],
        map: true  <--- this here
      },
      dist: {
        files: [{
          expand: true,
          cwd: '.tmp/',
          src: '{,*/}*.css',
          dest: '.tmp/'
        }]
      }
    },

    ...

    // Compiles Less to CSS
    less: {
      options: {
        paths: [
          '<%= yeoman.client %>/bower_components',
          '<%= yeoman.client %>/app',
          '<%= yeoman.client %>/components'
        ],
        sourceMap: true,    <--- this here
        sourceMapFileInline: true  <--- and this here
      },
      server: {
        files: {
          '.tmp/app/app.css' : '<%= yeoman.client %>/app/app.less'
        }
      },
    },

And pow, it works!
