### ISSUE TITLE
NPM Installs lodash 4.4 (or current) _.pairs

### ISSUE THREAD

**Issue by jbarngr** [gruntjs/grunt-contrib-less#305]
At least in Gitbash for windows, lodash will load with version current release instead of ^3. Normally this isn't an issue but in version 4 they rename `_.pairs` to `_.toPairs` and that breaks your `parseVariableOptions` function. 2 possible solutions to fix this. 

1. change dependencies to be `"lodash" : "~3.2.0"`, (or `"lodash" : "~3.10.1"` to use the most of version 3)
2. in the `parseVariableOptions` function check if `_.pairs` or `_.toPairs` exist and use the appropriate function.

[lodash change log](https://github.com/lodash/lodash/wiki/Changelog#v400)

**Comment by XhmikosR** [comment]
This should be fixed in 1.3.0 when it's published.
