### ISSUE TITLE
Compilation errors are not handled properly

### ISSUE THREAD

**Issue by fatfisz** [gruntjs/grunt-contrib-less#314]
I was running `grunt-contrib-watch` with `grunt-contrib-less` and other tasks, and I noticed that only `grunt-contrib-less` was behaving strangely: if a compilation error was encountered, everything just hung up.

After long search through `grount-contrib-watch` and `grunt` I am fairly certain that the problem lies with how `grunt-contrib-less` handles compilation errors.

So in the `less` task there is a `compileLess` function, which contains this code at the end:

``` js
return less.render(srcCode, options)
  .catch(function(err) {
    lessError(err, srcFile);
  });
```

As you can see, in case of an error a message is printed, and then - because nothing is returned from the function in `catch`, the promise is fulfilled with `undefined`.

The next step is this then:

``` js
compileLess(file, destFile, options)
  .then(function(output) {
    compiled.push(output.css);
    ...
```

But it should be obvious by now that this throws an error, because `output` is `undefined` (`compileLess` was fulfilled with it) and we can't get the `css` property of `undefined`.

Because there are no further error handlers, the error is just sent into nothingness and the `nextFileObj` function is not called. This seems like something that is not desired.

I'm not sure what's the appropriate fix here. Would rethrowing the error be ok?

``` js
  .catch(function(err) {
    lessError(err, srcFile);
    throw err;
  });
```

**Comment by fatfisz** [comment]
@XhmikosR Could you check this out please? This is a very annoying problem. And I have a fix ready for this, so almost no work from the maintainers required.

**Comment by XhmikosR** [comment]
I'm still waiting for @vladikoff to look at #322 and then we can check #315.

**Comment by leigeber** [comment]
Would love to see this one merged in. Bites me every time. Is there something outstanding any of us can help resolve or is this still waiting on @vladikoff? Thanks.
