### ISSUE TITLE
Ignore imports which cannot be found

### ISSUE THREAD

**Issue by karlbateman** [gruntjs/grunt-contrib-less#325]
I would really like an option to ignore `@imports` which do not resolve. The `strictImports` option does not seem to be doing anything if it's disabled by default.

**Comment by Rodrigo-Ludgero** [comment]
Hi @karlbateman ,

Perhaps this serves to fix, @import (optional) url('whatever.less');

http://lesscss.org/features/#import-options

http://lesscss.org/features/#import-options-optional

**Comment by karlbateman** [comment]
@Rodrigo-Ludgero That's a real gem 💎, thanks for that!

**Comment by karlbateman** [comment]
Closing thanks to @Rodrigo-Ludgero
