### ISSUE TITLE
UnhandledPromiseRejectionWarning crashes Grunt watch

### ISSUE THREAD

**Issue by krnlde** [gruntjs/grunt-contrib-less#329]
Grunt is crashing when having a less syntax error. The syntax error itself is handled correctly, and a growl notification is properly shown. After that a wild UnhandledPromiseRejectionWarning appears and crashes the Grunt watch task unrecoverably. The output for that is:

```
>> File "assets\less\project\thumbnails.less" changed.

Running "less:dev" (less) task
>> NameError: variable @i-am-not-defined is undefined in assets\less\project\thumbnails.less on line 6, column 16: >> 5    width: 400px;
>> 6    margin-right: @i-am-not-defined;
>> 7 }
Warning: Error compiling assets/less/index.less
(node:6672) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'css' of undefined
(node:6672) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The gruntfile config for less looks unsuspicious:
```
		less: {
			dev: {
				files: {
					'assets/css/index_raw.css': 'assets/less/index.less'
				}
			}
		},

...
		watch: {
			css: {
				files: ['assets/less/**/*.less'],
				tasks: ['less:dev', 'autoprefixer', 'clean:less', 'newer:copy:server'],
				options: {
					spawn: false
				}
			}
		}
...
```

The project that got me started was [micromata/bootstrap-kickstart](/micromata/bootstrap-kickstart)
I am using Windows 10 Pro (64bit), node v7.2.0, grunt-cli v1.2.0, grunt v1.0.1 and grunt-contrib-less v1.4.0

**Comment by mischah** [comment]
Hej there,

I had the same kind of error with another error message on node `5.x.x`

Just updated to node `6.9.1` and now its the same error message as above:

```
Running "watch" task
Waiting...
>> File "assets/less/alerts.less" changed.

Running "less:dev" (less) task
>> ParseError: Unrecognised input in assets/less/alerts.less on line 26, column 25:
>> 25 
>> 26 body {background: pink ;!important}
>> 27
Warning: Error compiling assets/less/index.less
(node:22210) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'css' of undefined
>> File "assets/less/alerts.less" changed.
```

My environment:
+ macOS Sierra
+ node `6.9.1`
+ grunt-cli `v1.2.0`
+ grunt `v1.0.1`
+ grunt-contrib-less `1.4.0`

**Comment by krnlde** [comment]
Possibly the same underlying problem: https://github.com/gruntjs/grunt-contrib-imagemin/issues/372

**Comment by tjdraper** [comment]
Any movement on this? I’m getting the same issue.

**Comment by fatfisz** [comment]
This is possibly related to #314, which was fixed and is merged. The only problem is that the version with the fix is not published yet.

**Comment by mischah** [comment]
Hej @XhmikosR,

any chance to release the current changes anytime soon 😘 

Thanks, Michael

**Comment by krnlde** [comment]
fyi the problem is still present in node 7.7.1.

**Comment by XhmikosR** [comment]
I'll try to have a look tomorrow and release a new patch version.

**Comment by mischah** [comment]
Thanks 💖

**Comment by XhmikosR** [comment]
Release v1.4.1. If this issue is fixed, let me know so that I close it.

**Comment by krnlde** [comment]
You made less great again. Thank you man :-*
