### ISSUE TITLE
Node 8.5.0 breaks task

### ISSUE THREAD

**Issue by jeroencornelissen** [gruntjs/grunt-contrib-less#336]
Hard to explain, but since updating to Node 8.5.0 my less task can't find imported files.

I run it in this directory:
`/var/www/current/httpdocs/modules/moduleB/desktop/main`

I get this error:
```
Running "less:compile" (less) task
>> FileError: '../../../../../generic/desktop/css/flexbox.less' wasn't found. Tried - ../../desktop/css/flexbox.less,../generic/desktop/css/flexbox.less,../../../../../generic/desktop/css/flexbox.less in ../../../ModuleB/desktop/main/styles.less on line 2, column 1:
>> 1 @import 'styles.less';
>> 2 @import '../../../../../desktop/css/flexbox.less';
>> 3
Warning: Error compiling main.less Use --force to continue`
```

If I switch back to Node 8.4.0 the task works fine.

**Comment by JurRutten** [comment]
+1

**Comment by arkadicolson** [comment]
Same issue here
+1

**Comment by MichielDilissen** [comment]
+1

**Comment by vladikoff** [comment]
Hm need to check if this is an issue in less or the task..

**Comment by jeroencornelissen** [comment]
Thx @vladikoff. We need to update Node because of the [security vulerability](https://nodejs.org/en/blog/vulnerability/oct-2017-dos/).

**Comment by vladikoff** [comment]
First look at this, all tests pass in node 8.5

**Comment by vladikoff** [comment]
Can somebody provide an example of their configuration, I'm trying to reproduce this issue locally?

**Comment by jeroencornelissen** [comment]
Rearranged my imports and that fixed the issue.
