### ISSUE TITLE
missing units after compilation 

### ISSUE THREAD

**Issue by parulmahajan1992** [gruntjs/grunt-contrib-less#338]
@var1: 2em;
@var2: 1/2em;

#myClass{
	width: @var1*@var2 ;
}

Output for this is:
#myClass{width:1em};

But if we interchange the variables as:
#myClass{
	width: @var2*@var1 ;
}

Output for this is: 
#myClass{width:1};

em is missing. :(

**Comment by XhmikosR** [comment]
Such issues should be reported upstream.
