### ISSUE TITLE
Less 3.0.0 update

### ISSUE THREAD

**Issue by bricss** [gruntjs/grunt-contrib-less#339]
Any plans for update? -> https://github.com/less/less.js/blob/master/CHANGELOG.md#300

**Comment by timhecker** [comment]
+1

**Comment by eleono83** [comment]
What about this update? -> [https://github.com/less/less.js/blob/master/CHANGELOG.md#300]

**Comment by panther7** [comment]
+1

**Comment by pierre-arlaud** [comment]
+1

**Comment by BartoszPiwek** [comment]
+1 $prop syntax !

**Comment by panther7** [comment]
Thank you

**Comment by vladikoff** [comment]
done.
