### ISSUE TITLE
@import .css files

### ISSUE THREAD

**Issue by gigablox** [gruntjs/grunt-contrib-less#41]
From the Official Documentation :

You can import both css and less files. Only less files import statements are processed, css file import statements are kept as they are. If you want to import a CSS file, and don’t want LESS to process it, just use the .css extension:

Is there a way to do this now?

**Comment by dmoskovsov** [comment]
@serheyShmyg thanks!

**Comment by andreibenhur** [comment]
yeah @serheyShmyg
thanks!

**Comment by dostiharise** [comment]
I guess you can also use 'inline' import option. - [Less - Import Options](http://lesscss.org/features/#import-options)

`@import (inline) path/to/my/file.css`
