### ISSUE TITLE
Sourcemaps with multiple src files:

### ISSUE THREAD

**Issue by phadej** [gruntjs/grunt-contrib-less#89]
The example is a code at https://github.com/phadej/relaxed-json/tree/c3667434eb211b0f745872793723dcffe6e304d4

When running `grunt less` output is:
```
Running "less:web" (less) task
File web.min.css.map created.
File web.min.css.map created.
File web.min.css created.
Original: 7798 bytes.
Minified: 5564 bytes.
```

Looks like `less` itself doesn't support multiple input files for the source maps, but I guess it good to have this *feature bug* at least documented.

**Comment by gelus** [comment]
@rmunson was your fix ever merged in? What remains on this issue?

**Comment by gelus** [comment]
Okay, below is my current work around and what I'll be implementing on the project for the intermittent period.

The theory is to auto generate a "main" less file, which is simply a file containing a bunch of @import statements to all the other less files and then compile that. After compiling I clear out the "main" file.  
This generates the source maps correctly and keeps me from needing to maintain a manual list of files.

it is a work around but for now it will do. If I get some time over the weekend I'll see if I can put together a PR that runs off the same theory.

My complete demo Gruntfile:
```javascript
module.exports = function(grunt) {
  grunt.initConfig({
    clean: {
      removeMainLess: ["main.less"]
    },
    less: {
      dev: {
        options: {
          sourceMap: true,
          sourceMapFilename: "css/demo.css.map",
          sourceMapURL: "file:///home/bmiller/lessTest/css/demo.css.map"
        },
        files: {
          "css/demo.css": "main.less"
        }
      }
    },
    "file-creator": {
      createMainLess: {
        "main.less": function(fs, fd, done) {
          grunt.file.glob("less/**/*.less", function(err, files) {
            files.forEach(function(file, i) {
                fs.writeSync(fd, '@import "'+file+'";\n');
            });
            done();
          });
        }
      }
    }
  });

  grunt.loadNpmTasks('grunt-contrib-less');
  grunt.loadNpmTasks('grunt-contrib-clean');
  grunt.loadNpmTasks('grunt-file-creator');

  grunt.registerTask('default', ["file-creator:createMainLess", 'less:dev', "clean:removeMainLess"]);
};

```

**Comment by zamber** [comment]
@gelus, looks good but the trade-offs are:
- No control over .less order (can be solved by file naming).
- Still does not map to .less directly but to the css generated in main.css.

**Comment by gelus** [comment]
@zamber 
file order was one of my thoughts too. For the work around, it is as simple as adding a sort to the grunt glob. ( or whatever other manual array manipulation you care to do ) 

```javascript
"file-creator": {
      createMainLess: {
        "main.less": function(fs, fd, done) {
          grunt.file.glob("less/**/*.less", function(err, files) {
            files.sort(function(a,b){
              //.... what ever sort of sorting you want to implement.
            });
            files.forEach(function(file, i) {
                fs.writeSync(fd, '@import "'+file+'";\n');
            });
            done();
          });
        }
      }
    }
```

Getting that functionality into a PR is going to take more thought.  Then again, we don't currently have that functionality when compiling multiple sources to one destination so it might be another bug all together.

It does map to the less directly. The main file ( the one auto generated by file-creator ) should be a less file, not a css file. You then compile that main.less file and less will create a source map that will point to the original file.

Here is a screen shot of the console using the result of the above set up:


![image](https://cloud.githubusercontent.com/assets/2098537/5864004/60fe37b4-a23b-11e4-85ab-57196cf4e5b1.png)

**Comment by rmunson** [comment]
@gelus, @zamber  - I think this is a better solution than what I done previously.  It's the same approach I take in my current workarounds as well... either create a master less file for the project, or have the grunttfile generate one.

It is documented a bit better in issue #203.

My pull request should probably be closed at this point, as it hasn't had traction in so long.  I'm glad to implement this option if neither of you want to take it on.

**Comment by gelus** [comment]
@rmunson awesome!  I'm glad you like it. 
I expect to have some spare time today and don't have another project right now. So I'm looking forward to implementing it.

Looking over your PR it seems this functionality needs to be place behind an option. Did you experience any other hang-ups I should watch out for?

**Comment by zamber** [comment]
@gelus, @rmunson I'm convinced. Thanks :+1:.

**Comment by gelus** [comment]
Alright! PR is in.
it works under the same theory as the work around and will be hidden under the option combineSourceFiles. Which will allow one to share variables and mixins across files ( per destination ) and cause sourceMaps to point to the correct location.

**Comment by sindresorhus** [comment]
https://github.com/gruntjs/grunt-contrib-less/pull/243#issuecomment-75196554

**Comment by gelus** [comment]
[#243 (comment)](https://github.com/gruntjs/grunt-contrib-less/pull/243#issuecomment-75565337)
