### ISSUE TITLE
sourceMapFilename does not support compiling multiple Less files

### ISSUE THREAD

**Issue by dbergey** [gruntjs/grunt-contrib-less#93]
I have two source Less files:

				files: {
					'public/dist/bootstrap.css': 'public/less/bootstrap.less',
					'public/dist/bootstrap-lib.css': 'public/less/bootstrap-lib.less'
				}

And I want to generate a sourcemap file for each one. Short of breaking the entire task into two, there's no way to specify sourceMapFilename in the options and not have it write the sourcemap files out on top of each other.

**Comment by chrismadrigal** [comment]
No solution? ¯\_(ツ)_/¯

**Comment by sindresorhus** [comment]
https://github.com/gruntjs/grunt-contrib-less/pull/243#issuecomment-75196554
